import { PageHero, Section } from '../../components/ui';

export const metadata = {
  title: 'Notice of Privacy Practices | Integrative Psychiatry',
  description: 'HIPAA Notice of Privacy Practices for Integrative Psychiatry.'
};

const sections = [
  { title: '1. Our Commitment to Your Privacy', body: ['At Integrative Psychiatry, we are dedicated to maintaining the privacy of your Protected Health Information. In providing psychiatric care, we create records regarding your medical history, symptoms, exams, test results, and treatment plans. We are required by law to maintain the confidentiality of this health information, provide you with this Notice of our legal duties and privacy practices, and notify you if a breach of your unsecured health information occurs.'] },
  { title: '2. How We May Use and Disclose Your Health Information', body: ['We may use and disclose your Protected Health Information for treatment, payment, and health care operations without your written authorization.', 'Treatment: We may use your information to provide, coordinate, or manage your health care. For example, Dr. Zelisko may share your records with your primary care physician or a therapist to ensure your care is coordinated.', 'Payment: We may use and disclose your information to bill and collect payment for services we provide. For example, we may share your diagnosis and treatment details with your insurance plan, if applicable, or a third-party billing service to process a claim or superbill.', 'Health Care Operations: We may use your information to run our practice, improve your care, and contact you when necessary. This includes quality assessment, business planning, and administrative services.'] },
  { title: '3. Special Situations: Connecticut and Federal Law', body: ['Connecticut imposes specific restrictions on the disclosure of mental health records. We strictly adhere to Connecticut General Statutes, including CGS § 52-146f, and other state laws that may be more protective than federal law.', 'Serious Threat to Health or Safety / Duty to Warn: Under Connecticut law, we may disclose your information if we believe, in good faith, that there is a substantial risk of imminent physical injury to you or another person. We will only share information with those reasonably able to prevent or lessen the threat, such as law enforcement, the target of the threat, or family members.', 'Mandated Reporting: We are required by law to report known or suspected abuse or neglect of children to the Connecticut Department of Children and Families, elderly persons to the Connecticut Department of Social Services, and persons with intellectual disabilities.', 'Judicial and Administrative Proceedings: We may disclose information in response to a court order or a specific subpoena compliant with Connecticut state requirements for psychiatric records.', 'Public Health: We may disclose information for public health activities, such as reporting adverse reactions to medications.'] },
  { title: '4. Psychotherapy Notes', body: ['Psychotherapy notes are treated differently from your general medical record. These are notes recorded by a mental health professional documenting or analyzing the contents of a conversation during a private counseling session.', 'We must obtain your specific written authorization to release psychotherapy notes, except for limited internal use, training, defense in legal proceedings, or disclosure required by the Department of Health and Human Services.'] },
  { title: '5. Uses Requiring Written Authorization', body: ['Uses and disclosures not otherwise permitted by law generally require your written authorization. This may include most uses and disclosures of psychotherapy notes, marketing communications where authorization is required, sale of Protected Health Information, and other uses not described in this Notice.', 'You may revoke a written authorization in writing at any time, except to the extent the practice has already relied on that authorization.'] },
  { title: '6. Your Rights Regarding Your Health Information', body: ['Right to Inspect and Copy: You have the right to inspect and obtain a copy of your medical record. Under Connecticut law, we may deny access if a provider reasonably determines that seeing the information would be detrimental to your physical or mental health or cause harm to another person.', 'Right to Amend: If you feel that health information we have about you is incorrect or incomplete, you may ask us to amend the information. We may deny your request if the information is accurate or was not created by us.', 'Right to an Accounting of Disclosures: You may request a list of certain disclosures we made of your health information, excluding disclosures for treatment, payment, or operations.', 'Right to Request Restrictions: You have the right to request a restriction or limitation on the health information we use or disclose about you. We are not required to agree to your request unless you are paying out-of-pocket in full and the disclosure is to a health plan for payment purposes.', 'Right to Confidential Communications: You have the right to request that we communicate with you about medical matters in a certain way or at a certain location.', 'Right to a Paper Copy: You have the right to receive a paper copy of this Notice upon request, even if you have agreed to receive it electronically.', 'Right to Breach Notification: You have the right to be notified if a breach of unsecured Protected Health Information affects you.'] },
  { title: '7. Complaints', body: ['If you believe your privacy rights have been violated, you may file a complaint with our office or with the U.S. Department of Health and Human Services Office for Civil Rights. You will not be penalized or retaliated against for filing a complaint.', 'To file a complaint with our office, contact Privacy Officer Douglas Zelisko, M.D., 45 South Main Street, Suite 111, West Hartford, CT 06107. Phone: 860.615.3629. Email: support@drzelisko.com.'] },
  { title: '8. Changes to This Notice', body: ['We reserve the right to change this Notice. We will post a copy of the current Notice on our website, drzelisko.com, and at our office location.'] }
];

function LegalSection({ section }) {
  return <section className="border-t border-slate-200 py-7 first:border-t-0 first:pt-0"><h2 className="text-2xl font-semibold tracking-tight text-slate-950">{section.title}</h2><div className="mt-4 space-y-4 text-lg leading-8 text-slate-700">{section.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></section>;
}

export default function NoticeOfPrivacyPracticesPage() {
  return <><PageHero eyebrow="Legal" title="Notice of Privacy Practices" subtitle="How medical information may be used and disclosed, and how patients can access this information." /><Section><article className="mx-auto max-w-4xl rounded-[2rem] border border-slate-200 bg-white p-8 shadow-sm"><div className="mb-8 rounded-2xl bg-[#edf8f1] p-5 text-[#173f42]"><p className="text-sm font-semibold uppercase tracking-[0.16em]">Effective Date: May 18, 2026</p><h2 className="mt-3 text-2xl font-semibold">Integrative Psychiatry · Douglas Zelisko, M.D.</h2><p className="mt-3 font-semibold leading-7">THIS NOTICE DESCRIBES HOW MEDICAL INFORMATION ABOUT YOU MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. PLEASE REVIEW IT CAREFULLY.</p></div>{sections.map((section) => <LegalSection key={section.title} section={section} />)}</article></Section></>;
}
