import { PageHero, Section } from '../../components/ui';

export const metadata = {
  title: 'Terms of Use | Integrative Psychiatry',
  description: 'Terms of Use for the Integrative Psychiatry website.'
};

const sections = [
  { title: '1. No Medical or Psychiatric Advice', body: ['The content on this Site, including text, graphics, images, and other material, is for informational and educational purposes only. None of the content on this Site constitutes medical or psychiatric advice, diagnosis, or treatment. Always seek the advice of your physician, psychiatrist, or other qualified health provider with any questions you may have regarding a medical or mental health condition. Never disregard professional medical advice or delay in seeking it because of something you have read on this Site.'] },
  { title: '2. No Doctor-Patient Relationship Established', body: ['Your use of this Site does not create a doctor-patient relationship. Transmission of information from this Site, submission of a contact form or questionnaire, or communication via email does not create a clinical relationship between you and Integrative Psychiatry. A formal doctor-patient relationship is only established after an official intake process, clinical evaluation, and a signed, written treatment agreement between both parties.', 'Submitting a contact form or good-fit questionnaire does not guarantee acceptance into care, scheduling availability, medication prescribing, or that the practice will be the appropriate level of care for your needs.'] },
  { title: '3. Telehealth Services and Jurisdictional Limitations', body: ['Integrative Psychiatry provides virtual psychiatric and mental health services to patients when clinically appropriate.', 'Location Requirements: In compliance with state licensing laws and regulations, telehealth services are only available to individuals who are physically located within the State of Connecticut at the time of their appointment.', 'Technical Requirements: Patients are responsible for ensuring they have a secure, private location and the necessary technology, such as a stable internet connection and compatible camera/microphone, to participate in virtual visits.', 'Clinical Suitability: Telehealth may not be clinically appropriate for all individuals or conditions. Integrative Psychiatry reserves the right to determine suitability for virtual care and may recommend or require in-person care or referrals to alternative providers if deemed clinically necessary.'] },
  { title: '4. Appointment Cancellation Policy', body: ['By scheduling an appointment with Integrative Psychiatry, you agree to our cancellation policy.', '24-Hour Notice Required: If you need to cancel or reschedule your appointment, you must provide at least 24 hours notice prior to your scheduled appointment time.', 'Late Cancellation Fees: Appointments cancelled, rescheduled, or missed with less than 24 hours notice will be subject to a cancellation charge.', 'Insurance Notice: Insurance companies do not provide reimbursement for missed appointments or late cancellation fees. You will be solely responsible for this charge out-of-pocket.'] },
  { title: '5. Not for Emergencies', body: ['This Site is not equipped to handle medical or mental health emergencies. If you are experiencing a life-threatening emergency, a severe mental health crisis, or are having thoughts of suicide, do not rely on this Site or communicate through it. Please call 911, go to the nearest emergency room, or call or text the Suicide & Crisis Lifeline at 988 immediately.'] },
  { title: '6. Patient Privacy and Secure Communication', body: ['We take privacy seriously. However, standard internet communication, including standard email and non-designated website communication, may not be completely secure.', 'Please do not submit urgent or emergency clinical information through this website. General email and non-designated website communications should not be used for sensitive clinical information.', 'If the practice provides a designated form, such as a contact form or good-fit questionnaire, information submitted through that form may be used for administrative screening and follow-up, but submitting a form does not establish a doctor-patient relationship.', 'Existing patients should use the official patient portal for clinical communication whenever possible or contact the office directly by phone.'] },
  { title: '7. Third-Party Links and Services', body: ['This Site may link to third-party platforms or services, including patient portal, scheduling, payment, insurance, or educational resources. Integrative Psychiatry is not responsible for the content, privacy practices, security, or availability of third-party websites or platforms. Use of third-party services may be subject to their own terms and privacy policies.'] },
  { title: '8. Contact Information', body: ['For questions regarding these Terms or to reach the practice for non-emergency administrative matters, please contact Integrative Psychiatry at drzelisko.com, 45 South Main Street, Suite 111, West Hartford, CT 06107. Phone: 860.615.3629. Email: support@drzelisko.com.'] },
  { title: '9. Intellectual Property', body: ['All content, logos, text, design elements, and graphics on this Site are the intellectual property of Integrative Psychiatry unless otherwise noted. You may view and print content for personal, non-commercial use only. You may not modify, copy, distribute, transmit, display, perform, reproduce, publish, or sell any information obtained from this Site without explicit written permission.'] },
  { title: '10. Limitation of Liability', body: ['Integrative Psychiatry, its owners, employees, and contractors provide this Site on an as-is and as-available basis. To the fullest extent permitted by law, we disclaim all warranties and shall not be liable for any direct, indirect, incidental, or consequential damages resulting from your use of, or inability to use, this Site or reliance on its contents.'] },
  { title: '11. Governing Law and Jurisdiction', body: ['These Terms are governed by and construed in accordance with the laws of the State of Connecticut, without regard to its conflict of law principles. Any legal action or proceeding arising out of your use of this Site shall be brought exclusively in a court of competent jurisdiction sitting in Connecticut.'] },
  { title: '12. Accessibility', body: ['If you have difficulty accessing any part of this website, please contact the office so we can try to provide the information in another format or assist you with access.'] },
  { title: '13. Modifications to Terms', body: ['We reserve the right to change, modify, or update these Terms at any time without prior notice. Your continued use of the Site after any changes are posted constitutes your acceptance of the updated Terms.'] }
];

function LegalSection({ section }) {
  return <section className="border-t border-slate-200 py-7 first:border-t-0 first:pt-0"><h2 className="text-2xl font-semibold tracking-tight text-slate-950">{section.title}</h2><div className="mt-4 space-y-4 text-lg leading-8 text-slate-700">{section.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></section>;
}

export default function TermsOfUsePage() {
  return <><PageHero eyebrow="Legal" title="Terms of Use" subtitle="Terms for using the Integrative Psychiatry website." /><Section><article className="mx-auto max-w-4xl rounded-[2rem] border border-slate-200 bg-white p-8 shadow-sm"><p className="mb-8 rounded-2xl bg-[#edf8f1] p-4 text-sm font-semibold uppercase tracking-[0.16em] text-[#173f42]">Effective Date: May 18, 2026</p>{sections.map((section) => <LegalSection key={section.title} section={section} />)}</article></Section></>;
}
