import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { AlertTriangle, ArrowRight, BookOpen, Calendar, CheckCircle2, ChevronDown, CreditCard, ExternalLink, FileText, HelpCircle, Home, Leaf, LockKeyhole, Mail, MapPin, Menu, MessageCircle, Monitor, Phone, Search, ShieldCheck, Sparkles, Stethoscope, UserRound, Users, X } from 'lucide-react';

const BRAND = { deep: '#173f42', teal: '#2f8c85', mint: '#9fcf9a', pale: '#edf8f1' };
const PRACTICE = { name: 'Integrative Psychiatry', doctor: 'Douglas Zelisko, MD', shortDoctor: 'Dr. Z', address: '45 South Main Street, Suite 111, West Hartford, CT 06107', phone: '860-615-3629', email: 'support@drzelisko.com', location: 'West Hartford, Connecticut' };
const ASSETS = { logo: '/logo.png', headshot: '/headshot.jpeg' };
const INTAKEQ = { accountId: '6785a5e3cc5e978c253acd8d', scriptSrc: 'https://intakeq.com/js/widget.min.js?1' };
const LINKS = { portal: 'https://drz.intakeq.com/portal', evaluationVirtual: 'https://link.drz.services/veval', evaluationOffice: 'https://link.drz.services/ieval', followUpOffice: 'https://link.drz.services/o', followUpVirtual: 'https://link.drz.services/v' };
const BOOKING_OPTIONS = [
  { key: 'evaluation-virtual', title: 'Virtual Psychiatric Evaluation Intake', subtitle: 'Start care with a comprehensive telehealth evaluation.', href: LINKS.evaluationVirtual, serviceId: '58193299-cfce-4354-b509-ce89f4aec3dc', icon: Monitor, badge: 'New patient', tone: 'from-[#9fcf9a] via-[#2f8c85] to-[#173f42]' },
  { key: 'evaluation-office', title: 'In-Office Psychiatric Evaluation Intake', subtitle: 'Begin care in a thoughtful, in-person setting in West Hartford.', href: LINKS.evaluationOffice, serviceId: 'f5586c2c-2dbd-4a55-878a-df83394ce608', icon: MapPin, badge: 'New patient', tone: 'from-[#d6e7c7] via-[#9fcf9a] to-[#2f8c85]' },
  { key: 'follow-up-office', title: 'In-Office Follow-Up', subtitle: 'Schedule an established-patient follow-up at the office.', href: LINKS.followUpOffice, serviceId: '20ee08a2-0586-4719-83fa-599c5aea1fc2', icon: Users, badge: 'Current patient', tone: 'from-[#173f42] via-[#2f8c85] to-[#9fcf9a]' },
  { key: 'follow-up-virtual', title: 'Virtual Follow-Up', subtitle: 'Continue established care by secure telehealth follow-up.', href: LINKS.followUpVirtual, serviceId: '57f67047-59ad-4edf-8ab1-db9f0c072bad', icon: Monitor, badge: 'Current patient', tone: 'from-[#24565a] via-[#2f8c85] to-[#9fcf9a]' },
];
const PAGES = [
  { id: 'home', path: '/', label: 'Home', icon: Home },
  { id: 'about', path: '/about', label: 'About', icon: UserRound },
  { id: 'services', path: '/services', label: 'Services', icon: Stethoscope },
  { id: 'resources', path: '/resources', label: 'Resources & FAQ', icon: BookOpen },
  { id: 'ketamine', path: '/ketamine-therapy', label: 'Ketamine', icon: Sparkles },
  { id: 'fees', path: '/fees-insurance', label: 'Fees', icon: CreditCard },
  { id: 'new-patients', path: '/new-patients', label: 'New Patients', icon: Calendar },
  { id: 'current-patients', path: '/current-patients', label: 'Current Patients', icon: Users },
  { id: 'contact', path: '/contact', label: 'Contact', icon: Mail },
];
const PAGE_BY_PATH = { ...Object.fromEntries(PAGES.map((page) => [page.path, page.id])), '/faq': 'resources', '/commentary': 'resources' };
const PATH_BY_PAGE = Object.fromEntries(PAGES.map((page) => [page.id, page.path]));
function getPageFromPath() { return typeof window === 'undefined' ? 'home' : PAGE_BY_PATH[window.location.pathname] || 'home'; }

const TRAINING = ['Amherst College', 'St. George’s University School of Medicine', 'Psychiatry residency at UConn School of Medicine', 'Board-certified psychiatrist'];
const SERVICES = [
  { icon: FileText, title: 'In-depth psychiatric evaluations', text: 'A full assessment of symptoms, history, lifestyle, medical context, goals, and treatment options.' },
  { icon: MessageCircle, title: 'Psychodynamic psychotherapy', text: 'A reflective approach that helps you understand patterns, emotions, relationships, and the deeper meaning behind symptoms.' },
  { icon: Stethoscope, title: 'Medication management', text: 'Thoughtful prescribing, side-effect review, and medication decisions integrated with the larger treatment plan.' },
  { icon: Leaf, title: 'Holistic treatment planning', text: 'Care may consider diet, exercise, sleep, stress physiology, supplements, medical factors, and whole-person wellness.' },
  { icon: Sparkles, title: 'Ketamine-assisted psychotherapy', text: 'A carefully screened option for selected patients, with preparation, monitoring, and integration.' },
  { icon: Search, title: 'Diagnostic clarity & second opinions', text: 'A fresh look when symptoms, diagnosis, or treatment history feel complicated or unclear.' },
];
const METHODS = ['Psychodynamic psychotherapy', 'Medication management', 'Integrative psychiatry', 'Ketamine-assisted therapy', 'CBT-informed strategies', 'Person-centered care', 'Mindfulness-informed care', 'Trauma-focused care', 'Family / marital and interpersonal therapy', 'Psychological testing and evaluation'];
const CONDITIONS = ['Anxiety', 'Depression and mood disorders', 'ADHD and focus concerns', 'Trauma and PTSD', 'Grief and loss', 'Relationship issues', 'Substance use and dual diagnosis', 'Eating disorders', 'Sleep concerns', 'Stress, self-esteem, and life transitions'];
const ARTICLES = [
  { title: 'What Is Holistic Psychiatry?', category: 'Whole-person care', text: 'A practical guide to psychiatry that considers mind, body, lifestyle, medical context, values, and meaning.' },
  { title: 'Beyond Medication: A Holistic View on Treating ADHD', category: 'ADHD', text: 'A whole-person view of ADHD that looks beyond the pill to sleep, nutrition, exercise, gut health, and behavioral strategies.' },
  { title: 'Feeling Anxious? 5 Integrative Approaches to Find Calm', category: 'Anxiety', text: 'Education on integrative strategies that may support calm alongside appropriate psychiatric care.' },
  { title: 'What to Expect at Your First Psychiatric Evaluation', category: 'Getting started', text: 'How an in-depth intake explores your story, symptoms, health context, and treatment goals.' },
  { title: 'Medication and Psychotherapy Together', category: 'Treatment planning', text: 'Why medication management and therapy can complement each other in a thoughtful plan.' },
  { title: 'Ketamine-Assisted Psychotherapy: What Patients Should Know', category: 'Ketamine therapy', text: 'A careful overview of screening, preparation, safety, and integration.' },
];
const FAQ_GROUPS = [
  { title: 'Holistic Care for Mental Wellness', items: [
    ['What is Integrative Psychiatry?', 'Integrative Psychiatry is a comprehensive, personalized approach to mental wellness that considers the whole person—mind, body, and spirit. It blends evidence-based medicine such as psychotherapy and pharmacology with complementary tools such as nutritional support, lifestyle coaching, and functional assessment when clinically appropriate.'],
    ['What is your core philosophy?', 'The philosophy is to move beyond symptom management and understand the complete picture of your health. Care is collaborative, respectful of autonomy, and designed around your goals, values, and life circumstances.'],
    ['How is your approach different from traditional psychiatry?', 'The approach is broader and more in-depth. Longer sessions allow time to understand personal history, lifestyle, physical health, belief systems, and treatment goals. Treatment may include psychotherapy, medication, functional assessment, and lifestyle changes.'],
  ] },
  { title: 'Our Philosophy of Care', items: [
    ['Who is Dr. Douglas Zelisko (Dr. Z)?', 'Dr. Douglas Zelisko, or Dr. Z, is the board-certified psychiatrist who leads the practice. He is passionate about holistic mental health care and treats patients as whole individuals, not collections of symptoms.'],
    ['What are Dr. Z’s qualifications?', 'Dr. Z earned his undergraduate degree from Amherst College and his MD from St. George’s University School of Medicine. He completed Psychiatry Residency at UConn School of Medicine.'],
  ] },
  { title: 'Services & Conditions Treated', items: [
    ['What types of services do you offer?', 'Services include psychiatric evaluations, diagnostic assessments, second-opinion consultations, individual psychotherapy, couples counseling, medication management, ketamine-assisted psychotherapy, smoking cessation, relapse prevention, and selected wellness/lifestyle support.'],
    ['What is Ketamine-Assisted Psychotherapy?', 'Ketamine-Assisted Psychotherapy may be considered for selected patients after careful psychiatric evaluation, medical screening, preparation, informed consent, and monitoring. It is not appropriate for everyone.'],
    ['What conditions do you commonly treat?', 'Common concerns include depression, anxiety, mood disorders, PTSD and trauma, ADD/ADHD, eating disorders, substance use disorders, sleep disorders, stress, relationship issues, and psych-oncology support.'],
  ] },
  { title: 'Getting Started & Logistics', items: [
    ['How can I schedule my first appointment?', 'New patients can book a Psychiatric Evaluation Intake Appointment directly online. Choose virtual or in-office scheduling from the New Patients page.'],
    ['What should I expect during my first full appointment?', 'The first comprehensive evaluation is an in-depth session designed to understand you as a whole person, including personal and family history, current challenges, lifestyle factors, medical context, and goals.'],
    ['How long are typical appointments?', 'Sessions are longer than the industry standard, ranging from 30 minutes for some follow-up visits to 2 hours for initial comprehensive evaluations or in-depth psychotherapy sessions.'],
    ['Do you accept insurance?', 'The practice may operate out-of-network and may provide superbills. Insurance-based options may also be available through partner platforms for eligible plans. Please verify before scheduling.'],
  ] },
];
function Button({ children, onClick, href, variant = 'primary', className = '', external = false }) { const base = 'inline-flex items-center justify-center rounded-2xl px-5 py-3 text-sm font-semibold transition'; const styles = { primary: 'bg-[#173f42] text-white hover:bg-[#24565a]', dark: 'bg-slate-950 text-white hover:bg-slate-800', outline: 'border border-slate-300 bg-white text-slate-950 hover:bg-slate-50', ghost: 'bg-transparent text-slate-700 hover:bg-slate-100', light: 'border border-white/30 bg-white text-[#173f42] hover:bg-[#edf8f1]' }[variant]; if (href) return <a href={href} target={external ? '_blank' : undefined} rel={external ? 'noreferrer' : undefined} className={`${base} ${styles} ${className}`}>{children}</a>; return <button onClick={onClick} className={`${base} ${styles} ${className}`}>{children}</button>; }
function ExternalButton(props) { return <Button {...props} external>{props.children}<ExternalLink className="ml-2 h-4 w-4" /></Button>; }
function Card({ children, className = '' }) { return <div className={`rounded-[1.75rem] border border-slate-200 bg-white shadow-sm ${className}`}>{children}</div>; }
function Section({ children, className = '' }) { return <section className={`py-20 ${className}`}><div className="mx-auto max-w-7xl px-6 lg:px-8">{children}</div></section>; }
function SectionHeading({ eyebrow, title, subtitle }) { return <div className="mx-auto mb-12 max-w-3xl text-center">{eyebrow && <p className="mb-3 text-sm font-semibold uppercase tracking-[0.22em] text-[#2f8c85]">{eyebrow}</p>}<h2 className="text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">{title}</h2>{subtitle && <p className="mt-4 text-lg leading-8 text-slate-700">{subtitle}</p>}</div>; }
function PageHero({ eyebrow, title, subtitle, icon: Icon }) { return <section className="bg-[radial-gradient(circle_at_top_left,#edf8f1,transparent_40%),linear-gradient(180deg,#ffffff,#f8fafc)] py-20"><div className="mx-auto max-w-5xl px-6 text-center">{Icon && <div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-3xl bg-[#173f42] text-white"><Icon className="h-8 w-8" /></div>}<p className="mb-3 text-sm font-semibold uppercase tracking-[0.22em] text-[#2f8c85]">{eyebrow}</p><h1 className="text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">{title}</h1>{subtitle && <p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-slate-700">{subtitle}</p>}</div></section>; }
function Header({ page, navigate }) { const [open, setOpen] = useState(false); const go = (id) => { setOpen(false); navigate(id); }; return <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-8"><button onClick={() => go('home')} className="flex items-center gap-3 text-left"><img src={ASSETS.logo} alt="Integrative Psychiatry logo" className="h-12 w-12 rounded-2xl object-contain" onError={(e)=>{e.currentTarget.style.display='none'}} /><div><p className="text-sm font-semibold text-[#173f42]">{PRACTICE.name}</p><p className="text-xs text-slate-600">{PRACTICE.doctor}</p></div></button><nav className="hidden items-center gap-4 lg:flex">{PAGES.map((item) => <button key={item.id} onClick={() => go(item.id)} className={`text-sm font-medium ${page === item.id ? 'text-[#2f8c85]' : 'text-slate-700 hover:text-slate-950'}`}>{item.label}</button>)}</nav><div className="hidden items-center gap-3 lg:flex"><Button href={LINKS.portal} external variant="ghost"><LockKeyhole className="mr-2 h-4 w-4" /> Portal</Button><Button onClick={() => go('new-patients')}>Book Now</Button></div><Button variant="outline" className="lg:hidden" onClick={() => setOpen(!open)}>{open ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}</Button></div>{open && <div className="border-t border-slate-200 bg-white px-6 py-5 lg:hidden"><div className="grid gap-2">{PAGES.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => go(item.id)} className="flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-medium text-slate-700"><Icon className="h-4 w-4" /> {item.label}</button>; })}</div></div>}</header>; }
function Footer({ navigate }) { return <footer className="border-t border-slate-200 bg-white py-10"><div className="mx-auto grid max-w-7xl gap-8 px-6 text-sm text-slate-600 lg:grid-cols-2 lg:px-8"><div><p className="font-semibold text-[#173f42]">{PRACTICE.name} | {PRACTICE.doctor}</p><p className="mt-2">{PRACTICE.address}</p><p>{PRACTICE.phone} · {PRACTICE.email}</p><div className="mt-5 flex flex-wrap gap-3">{PAGES.map((item) => <button key={item.id} onClick={() => navigate(item.id)} className="hover:text-slate-950">{item.label}</button>)}<a href={LINKS.portal} target="_blank" rel="noreferrer" className="hover:text-slate-950">Patient Portal</a></div></div><div className="lg:text-right"><p>This website provides general information and is not medical advice.</p><p className="mt-4">© {new Date().getFullYear()} Integrative Psychiatry. All rights reserved.</p></div></div></footer>; }
function IntakeQWidget({ option }) { useEffect(() => { if (!option || typeof document === 'undefined') return; const c = document.getElementById('intakeq'); if (c) c.innerHTML = ''; document.querySelectorAll('script[data-intakeq-widget="true"]').forEach((s) => s.remove()); window.intakeq = INTAKEQ.accountId; window.intakeqServiceId = option.serviceId; const script = document.createElement('script'); script.type = 'text/javascript'; script.async = true; script.src = INTAKEQ.scriptSrc; script.dataset.intakeqWidget = 'true'; document.head.appendChild(script); }, [option]); return <div className="relative overflow-hidden rounded-[2rem] border border-white/20 bg-white shadow-2xl shadow-[#173f42]/20"><div className={`h-2 bg-gradient-to-r ${option.tone}`} /><div className="grid gap-0 lg:grid-cols-[0.42fr_0.58fr]"><div className="relative overflow-hidden bg-[#173f42] p-8 text-white"><p className="text-sm font-semibold uppercase tracking-[0.22em] text-[#d6e7c7]">PracticeQ booking scheduler</p><h3 className="mt-4 text-3xl font-semibold tracking-tight text-white">{option.title}</h3><p className="mt-4 leading-7 text-slate-100">Secure scheduling is powered by IntakeQ / PracticeQ.</p><div className="mt-8 space-y-3 text-sm text-white">{['Secure IntakeQ widget', option.badge + ' scheduling path', 'Direct fallback link included'].map((item) => <div key={item} className="flex items-center gap-3 text-white"><CheckCircle2 className="h-5 w-5 text-[#9fcf9a]" /><span className="text-white">{item}</span></div>)}</div><ExternalButton href={option.href} variant="light" className="mt-8 w-full">Open in New Window</ExternalButton></div><div className="bg-[radial-gradient(circle_at_top,#edf8f1,transparent_35%),#ffffff] p-4 sm:p-6"><div className="mx-auto max-w-[720px] rounded-[1.5rem] border border-slate-200 bg-white p-3 shadow-inner shadow-slate-100"><div id="intakeq" style={{ maxWidth: '720px', width: '100%' }} /></div><p className="mt-4 text-center text-sm text-slate-500">If the scheduler does not load, <a href={option.href} target="_blank" rel="noreferrer" className="font-semibold text-[#173f42] underline">open the secure booking page</a>.</p></div></div></div>; }
function BookingCard({ option, selected, onSelect }) { const Icon = option.icon; return <motion.button type="button" onClick={() => onSelect(option.key)} whileHover={{ y: -6 }} whileTap={{ scale: .99 }} className={`group relative overflow-hidden rounded-[2rem] border p-[1px] text-left shadow-xl transition ${selected ? 'border-[#9fcf9a] shadow-[#173f42]/20' : 'border-slate-200 shadow-slate-200/80 hover:border-[#9fcf9a]'}`}><div className={`absolute inset-x-0 top-0 h-1.5 bg-gradient-to-r ${option.tone}`} /><div className="relative h-full rounded-[1.95rem] bg-white p-6"><div className={`absolute -right-10 -top-10 h-32 w-32 rounded-full bg-gradient-to-br ${option.tone} opacity-10 blur-2xl transition group-hover:opacity-20`} /><div className="flex items-start justify-between gap-4"><div className={`flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br ${option.tone} text-white shadow-lg`}><Icon className="h-7 w-7" /></div><span className={`rounded-full px-3 py-1 text-xs font-semibold uppercase tracking-wide ${selected ? 'bg-[#173f42] text-white' : 'bg-slate-100 text-slate-600'}`}>{option.badge}</span></div><h3 className="mt-6 text-2xl font-semibold text-slate-950">{option.title}</h3><p className="mt-3 leading-7 text-slate-600">{option.subtitle}</p><div className="mt-6 flex items-center justify-between text-sm font-semibold text-[#2f8c85]"><span>{selected ? 'Selected appointment' : 'Select appointment'}</span><ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></div></div></motion.button>; }
function BookingExperience({ defaultKey = 'evaluation-virtual', mode = 'all' }) { const options = mode === 'new' ? BOOKING_OPTIONS.slice(0, 2) : mode === 'current' ? BOOKING_OPTIONS.slice(2) : BOOKING_OPTIONS; const [selectedKey, setSelectedKey] = useState(defaultKey); const selected = options.find((o) => o.key === selectedKey) || options[0]; return <div className="relative"><div className="pointer-events-none absolute inset-0 -z-10 rounded-[3rem] bg-gradient-to-br from-[#edf8f1] via-white to-[#d6e7c7] blur-3xl" /><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{options.map((o) => <BookingCard key={o.key} option={o} selected={selected.key === o.key} onSelect={setSelectedKey} />)}</div><div className="mt-8"><IntakeQWidget option={selected} /></div></div>; }
function HomePage({ navigate }) { return <><section className="relative overflow-hidden bg-[radial-gradient(circle_at_top_left,#edf8f1,transparent_38%),linear-gradient(180deg,#ffffff,#f8fafc)] py-20 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8"><motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}><img src={ASSETS.logo} alt="Integrative Psychiatry logo" className="mb-6 h-24 w-24 object-contain" onError={(e)=>{e.currentTarget.style.display='none'}} /><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#9fcf9a] bg-white px-4 py-2 text-sm text-[#173f42] shadow-sm"><ShieldCheck className="h-4 w-4" /> Board-certified psychiatry in Connecticut</div><h1 className="max-w-4xl text-4xl font-semibold tracking-tight text-slate-950 sm:text-6xl">Holistic psychiatry rooted in you.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-700">Personalized mental health care that treats the whole you—mind, body, and spirit. The practice provides time for in-depth assessment, individualized treatment planning, and a collaborative relationship where you feel heard and supported.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button onClick={() => navigate('new-patients')} variant="dark">Book Evaluation <ArrowRight className="ml-2 h-4 w-4" /></Button><Button onClick={() => navigate('resources')} variant="outline">Resources & FAQ</Button></div></motion.div><div className="relative"><div className="absolute -inset-4 rounded-[2.5rem] bg-gradient-to-br from-[#9fcf9a]/30 to-[#173f42]/20 blur-2xl" /><img src={ASSETS.headshot} alt="Dr. Douglas Zelisko portrait" className="relative mx-auto max-h-[560px] rounded-[2rem] object-cover shadow-2xl" onError={(e)=>{e.currentTarget.style.display='none'}} /></div></div></section><PracticeDeepDive /><BookingOverview navigate={navigate} /><ServicePreview navigate={navigate} /></>; }
function PracticeDeepDive() { return <Section><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="mb-3 text-sm font-semibold uppercase tracking-[0.22em] text-[#2f8c85]">The practice</p><h2 className="text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">A wider lens for mental health.</h2><p className="mt-6 text-lg leading-8 text-slate-700">Care focuses on adults navigating anxiety, depression, grief, relationship issues, trauma, focus concerns, physical health challenges, and complex life transitions. Dr. Z primarily practices psychodynamic psychotherapy while drawing from other modalities when they better fit the person and the moment.</p><p className="mt-4 text-lg leading-8 text-slate-700">Treatment plans may include psychotherapy, medication management, diet and exercise considerations, supplement review, ketamine-assisted therapy, and complementary approaches that support a personalized path toward lasting wellness.</p></div><div className="grid gap-4 sm:grid-cols-2">{METHODS.map((m) => <Card key={m}><div className="p-5"><CheckCircle2 className="h-5 w-5 text-[#2f8c85]" /><h3 className="mt-3 font-semibold text-slate-950">{m}</h3></div></Card>)}</div></div><div className="mt-12 rounded-[2rem] bg-[#173f42] p-8 text-white"><h3 className="text-2xl font-semibold text-white">Common areas of care</h3><div className="mt-5 flex flex-wrap gap-2">{CONDITIONS.map((c) => <span key={c} className="rounded-full bg-white/10 px-4 py-2 text-sm text-white">{c}</span>)}</div></div></Section>; }
function BookingOverview({ navigate }) { return <Section className="bg-slate-50"><SectionHeading eyebrow="Appointments" title="A beautiful, secure way to schedule." subtitle="Select the appointment path that fits, then complete the official IntakeQ booking widget right on the page." /><BookingExperience mode="all" defaultKey="evaluation-virtual" /><div className="mt-8 text-center"><Button onClick={() => navigate('current-patients')} variant="outline">View Follow-Up Booking Options</Button></div></Section>; }
function ServicePreview({ navigate }) { return <Section><SectionHeading eyebrow="Services" title="Comprehensive care solutions." subtitle="Psychotherapy, medication management, evaluations, lifestyle recommendations, and other integrative options." /><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{SERVICES.map((s) => { const Icon = s.icon; return <Card key={s.title} className="transition hover:-translate-y-1 hover:shadow-xl"><div className="p-7"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#edf8f1] text-[#173f42]"><Icon className="h-6 w-6" /></div><h3 className="mt-5 text-xl font-semibold text-slate-950">{s.title}</h3><p className="mt-3 leading-7 text-slate-600">{s.text}</p></div></Card>; })}</div><div className="mt-10 text-center"><Button onClick={() => navigate('services')} variant="outline">View All Services</Button></div></Section>; }
function AboutPage() { return <><PageHero icon={UserRound} eyebrow="Meet Dr. Z" title="Your partner in healing." subtitle="Dr. Douglas Zelisko, affectionately known as Dr. Z, is a board-certified psychiatrist with a deep commitment to holistic, personalized mental health care." /><Section><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><Card className="bg-slate-50"><div className="p-8"><img src={ASSETS.headshot} alt="Dr. Douglas Zelisko" className="h-64 w-full rounded-[1.5rem] object-cover object-top" onError={(e)=>{e.currentTarget.style.display='none'}} /><h3 className="mt-6 text-2xl font-semibold text-slate-950">{PRACTICE.doctor}</h3><p className="mt-2 text-slate-600">Board-certified psychiatrist</p><div className="mt-6 space-y-3 text-sm text-slate-700">{TRAINING.map((item) => <p key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 text-[#2f8c85]" /> {item}</p>)}</div></div></Card><div className="space-y-6 text-lg leading-8 text-slate-700"><p>Leading the practice is Dr. Douglas Zelisko, known warmly as Dr. Z. He brings a passion for holistic mental health care and a thoughtful, patient-centered style to every interaction.</p><p>Dr. Zelisko’s academic foundation includes degrees from Amherst College and St. George’s University School of Medicine, followed by psychiatry residency training at UConn School of Medicine.</p><p>In treatment, Dr. Z integrates psychotherapy, medication management, genetic insights when clinically useful, and comprehensive lifestyle coaching. The goal is to support each person’s unique journey with care that is collaborative, respectful of autonomy, and tailored to real-life goals.</p><p>Beyond his clinical work, Dr. Z enjoys road biking, running, and discovering mid-century modern design treasures.</p></div></div></Section></>; }
function ServicesPage({ navigate }) { return <><PageHero icon={Stethoscope} eyebrow="Services" title="Comprehensive care solutions." subtitle="Personalized care for a broad spectrum of concerns, delivered through an integrative, whole-person lens." /><ServicePreview navigate={navigate} /><PracticeDeepDive /></>; }
function KetaminePage({ navigate }) { return <><PageHero icon={Sparkles} eyebrow="Ketamine-Assisted Psychotherapy" title="A careful, clinically guided option for selected patients." subtitle="Ketamine-assisted psychotherapy may be considered only after evaluation, screening, preparation, informed consent, and safety review." /><Section><div className="grid gap-8 lg:grid-cols-[1fr_.8fr]"><div className="space-y-6 text-lg leading-8 text-slate-700"><p>Ketamine-assisted psychotherapy may be considered for carefully selected adults after psychiatric evaluation, medical screening, preparation, informed consent, and monitoring.</p><p>The psychotherapy component matters. Preparation and integration can help patients make sense of the experience and connect insights to daily life.</p></div><Card className="bg-[#173f42] text-white shadow-xl"><div className="p-8"><h3 className="text-2xl font-semibold text-white">A responsible process includes:</h3><div className="mt-6 space-y-4">{['Clinical evaluation', 'Medical and medication review', 'Informed consent', 'Preparation', 'Monitoring', 'Psychotherapy integration'].map((item) => <div key={item} className="flex items-center gap-3 rounded-2xl bg-white/10 p-4 text-white"><CheckCircle2 className="h-5 w-5 text-[#9fcf9a]" /><span className="font-medium text-white">{item}</span></div>)}</div></div></Card></div><div className="mt-10 text-center"><Button onClick={() => navigate('new-patients')}>Book an Evaluation</Button></div></Section></>; }
function FeesPage({ navigate }) { return <><PageHero icon={CreditCard} eyebrow="Fees & Insurance" title="Clear payment information before you begin." subtitle="Insurance and payment pathways should be confirmed before scheduling." /><Section><Card className="mx-auto max-w-5xl"><div className="grid gap-8 p-8 md:grid-cols-2"><div><h3 className="text-2xl font-semibold text-slate-950">Private practice care</h3><p className="mt-3 leading-7 text-slate-700">The private practice may operate out-of-network and may provide superbills when appropriate.</p></div><div><h3 className="text-2xl font-semibold text-slate-950">Insurance-based options</h3><p className="mt-3 leading-7 text-slate-700">Insurance-based appointments may be available through Headway for eligible plans. Please verify before scheduling.</p></div></div><div className="px-8 pb-8"><Button onClick={() => navigate('contact')} variant="outline">Ask About Payment Options</Button></div></Card></Section></>; }
function NewPatientsPage() { return <><PageHero icon={Calendar} eyebrow="New Patients" title="Book a Psychiatric Evaluation Intake Appointment." subtitle="Choose virtual or in-office care, then complete the official IntakeQ scheduling widget." /><Section><BookingExperience mode="new" defaultKey="evaluation-virtual" /></Section></>; }
function CurrentPatientsPage() { return <><PageHero icon={Users} eyebrow="Current Patients" title="Follow-up appointments and patient portal access." subtitle="Use secure PracticeQ / IntakeQ links for follow-up scheduling and established-patient portal access." /><Section><BookingExperience mode="current" defaultKey="follow-up-virtual" /><div className="mt-10 grid gap-6 lg:grid-cols-2"><Card className="border-[#9fcf9a] bg-[#173f42] text-white shadow-xl"><div className="p-7"><LockKeyhole className="h-7 w-7 text-[#9fcf9a]" /><h3 className="mt-6 text-2xl font-semibold text-white">Patient Portal</h3><p className="mt-3 leading-7 text-white">Open the PracticeQ / IntakeQ portal for forms, secure messages, and office workflows.</p><ExternalButton href={LINKS.portal} variant="light" className="mt-6 w-full">Open Portal</ExternalButton></div></Card><div className="rounded-[1.75rem] border border-red-200 bg-red-50 p-7 text-red-950"><AlertTriangle className="h-7 w-7" /><h3 className="mt-5 text-2xl font-semibold">Urgent concerns</h3><p className="mt-3 leading-7">Do not use online scheduling or the portal for emergencies. Call 911, go to the nearest emergency department, or call/text 988 for mental health crisis support.</p></div></div></Section></>; }
function ResourcesPage() { const [open, setOpen] = useState('Holistic Care for Mental Wellness-0'); return <><PageHero icon={BookOpen} eyebrow="Resources & FAQ" title="Learn, prepare, and get answers." subtitle="Educational resources and frequently asked questions in one place." /><Section><SectionHeading eyebrow="Commentary" title="Featured resources" subtitle="These article topics reflect the practice’s whole-person perspective on mental health." /><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{ARTICLES.map((a) => <Card key={a.title}><div className="p-7"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#2f8c85]">{a.category}</p><h3 className="mt-4 text-xl font-semibold text-slate-950">{a.title}</h3><p className="mt-3 leading-7 text-slate-600">{a.text}</p></div></Card>)}</div></Section><Section className="bg-slate-50"><SectionHeading eyebrow="FAQ" title="Frequently asked questions" subtitle="Answers adapted from the current FAQ content, with updated booking and location language." /><div className="mx-auto max-w-5xl space-y-10">{FAQ_GROUPS.map((group) => <div key={group.title}><h2 className="mb-4 text-2xl font-semibold text-[#173f42]">{group.title}</h2><div className="space-y-3">{group.items.map(([q, a], i) => { const key = `${group.title}-${i}`; return <div key={q} className="rounded-2xl border border-slate-200 bg-white shadow-sm"><button className="flex w-full items-center justify-between gap-4 p-5 text-left" onClick={() => setOpen(open === key ? '' : key)}><span className="text-lg font-semibold text-slate-950">{q}</span><ChevronDown className={`h-5 w-5 shrink-0 text-slate-500 transition ${open === key ? 'rotate-180' : ''}`} /></button>{open === key && <p className="px-5 pb-5 leading-7 text-slate-700">{a}</p>}</div>; })}</div></div>)}</div></Section></>; }
function ContactPage({ navigate }) { return <><PageHero icon={Mail} eyebrow="Contact" title="Start with the right next step." subtitle="Book directly, open the patient portal, or contact the practice for administrative questions." /><Section className="bg-[#173f42] text-white"><div className="grid gap-8 lg:grid-cols-2"><Card className="border-white/10 bg-white/5 text-white"><div className="p-8"><h3 className="text-2xl font-semibold text-white">Office information</h3><div className="mt-6 space-y-4 text-white"><p className="flex gap-3"><MapPin className="mt-1 h-5 w-5 text-[#9fcf9a]" /> {PRACTICE.address}</p><p className="flex gap-3"><Phone className="mt-1 h-5 w-5 text-[#9fcf9a]" /> {PRACTICE.phone}</p><p className="flex gap-3"><Mail className="mt-1 h-5 w-5 text-[#9fcf9a]" /> {PRACTICE.email}</p></div><div className="mt-6 grid gap-3"><Button onClick={() => navigate('new-patients')} variant="light">Book New Patient Evaluation</Button><Button onClick={() => navigate('current-patients')} variant="outline" className="border-white/30 bg-transparent text-white hover:bg-white/10">Current Patient Links</Button><ExternalButton href={LINKS.portal} variant="light" className="w-full">Open Patient Portal</ExternalButton></div></div></Card><div className="rounded-[2rem] border border-amber-200/30 bg-white/5 p-8"><AlertTriangle className="h-6 w-6 text-amber-100" /><h3 className="mt-4 text-2xl font-semibold text-white">For urgent needs</h3><p className="mt-3 leading-7 text-white">This website and online booking are not monitored for urgent clinical needs. Use emergency or crisis resources when needed.</p></div></div></Section></>; }
function AppContent({ page, navigate }) { const content = { home: <HomePage navigate={navigate} />, about: <AboutPage />, services: <ServicesPage navigate={navigate} />, resources: <ResourcesPage />, ketamine: <KetaminePage navigate={navigate} />, fees: <FeesPage navigate={navigate} />, 'new-patients': <NewPatientsPage />, 'current-patients': <CurrentPatientsPage />, contact: <ContactPage navigate={navigate} /> }; return content[page] || content.home; }
export default function App() { const [page, setPage] = useState(getPageFromPath); useEffect(() => { const h = () => setPage(getPageFromPath()); window.addEventListener('popstate', h); return () => window.removeEventListener('popstate', h); }, []); function navigate(id) { const path = PATH_BY_PAGE[id] || '/'; if (window.location.pathname !== path) window.history.pushState({}, '', path); setPage(id); window.scrollTo({ top: 0, behavior: 'smooth' }); } return <div className="min-h-screen bg-white font-sans text-slate-950"><Header page={page} navigate={navigate} /><main><AppContent page={page} navigate={navigate} /></main><Footer navigate={navigate} /></div>; }
