<?php
/**
 * Copy this file to api/config.php on Hostinger.
 * Do NOT commit api/config.php to GitHub.
 */
return [
    // Required: Quo/OpenPhone API key. Store only on Hostinger, never in frontend JS.
    'quo_api_key' => 'PASTE_QUO_OPENPHONE_API_KEY_HERE',

    // Required: Your Quo/OpenPhone phone number ID, usually starts with PN.
    // Quo/OpenPhone's API sends SMS via POST https://api.openphone.com/v1/messages.
    'quo_from' => 'PNxxxxxxxxxxxxxxxx',

    // Optional: Quo/OpenPhone user ID, usually starts with US. Leave blank if not needed.
    'quo_user_id' => '',

    // Optional: staff/admin SMS destination in E.164 format, e.g. +18605551212.
    // Keep staff alerts neutral. Do not include reason for care or clinical details in SMS.
    'staff_sms_to' => '+1XXXXXXXXXX',

    // Whether to send a neutral confirmation SMS to patients when they consent to texting.
    'send_patient_sms' => true,

    // Whether to send a neutral staff alert SMS.
    'send_staff_sms' => true,

    // Optional: encrypted local storage. Leave false unless Hostinger is approved for PHI handling.
    // If enabled, set storage_key to a 32-byte base64 key generated by: php -r "echo base64_encode(random_bytes(32));"
    'enable_encrypted_storage' => false,
    'storage_key' => 'PASTE_BASE64_32_BYTE_KEY_HERE',

    // Optional: admin notification email. Strongly recommended to keep disabled for PHI.
    'enable_email' => false,
    'admin_email' => 'support@drzelisko.com',

    // CORS: set this to your production domain, e.g. https://drzelisko.com
    'allowed_origin' => 'https://drzelisko.com',
];
